### ISSUE TITLE
Why do the mass matrix functions depend on qdot?

### ISSUE THREAD

**Issue by mshoe** [dilevin/CSC417-a3-finite-elements-3d#1]
I'm unsure why the mass matrix functions like mass_matrix_mesh and mass_matrix_linear_tetrahedron take qdot as input.

**Comment by dilevin** [comment]
To put it plainly -- its a test to see if you understand what you do and don't need. 

Remember you don't have to use all the inputs to each function -- the required variables are a subset of what is sent into each function. Sometimes you'll need everything, sometimes you won't.
