### ISSUE TITLE
N is not defined

### ISSUE THREAD

**Issue by YellPika** [dilevin/CSC417-a3-finite-elements-3d#2]
The matrix N is not defined in the section **The Kinetic Energy of a Single Tetrahedron**.

**Comment by dilevin** [comment]
<img width="586" alt="image" src="https://user-images.githubusercontent.com/1903521/66531098-97ac5580-ead8-11e9-8b41-9223d6f4ace6.png">

It's defined in this underbrace. It's small but its there :)

**Comment by dilevin** [comment]
here phi's are the shape functions (which are the barycentric coordinates)

**Comment by YellPika** [comment]
Missed that, thanks!
