### ISSUE TITLE
Readme Typo

### ISSUE THREAD

**Issue by honglin-c** [dilevin/CSC417-a3-finite-elements-3d#3]
There seem to be some typos in README.md. :)

1. On line 116: 
![image](https://user-images.githubusercontent.com/24607222/66710571-5ff81480-ed49-11e9-9882-865503877d3e.png)

2. On line 182, should it be X2 = X1 + dX here?
![image](https://user-images.githubusercontent.com/24607222/66710579-8cac2c00-ed49-11e9-847b-2b77e89cbbdb.png)

**Comment by dilevin** [comment]
Thanks, I've fixed these
