### ISSUE TITLE
Newton's method readme typo?

### ISSUE THREAD

**Issue by mshoe** [dilevin/CSC417-a3-finite-elements-3d#8]
In the Newton's Method section, I believe there should be a delta t here in front of delta qdot:

![image](https://user-images.githubusercontent.com/16711741/66975490-a365c200-f06c-11e9-9734-5ffa1e5ca022.png)

**Comment by mshoe** [comment]
Hmm actually I'm not sure if I what I said is correct, but something seems off about this since it is adding an incremental velocity vector to a position vector.

**Comment by dilevin** [comment]
Ah yes that section is not well written at all. I've re done it -- hopefully it is clearer now.
