### ISSUE TITLE
build_skinning_matrix.h typo

### ISSUE THREAD

**Issue by abhimadan** [dilevin/CSC417-a3-finite-elements-3d#9]
The comment says the following:
https://github.com/dilevin/CSC2549-a3-finite-elements-3d/blob/71e4faa1d2ab2a688d9a2684232f0d91e5a7d010/include/build_skinning_matrix.h#L9

However, the dimensions should really be `l x n`, as this matrix isn't used to multiply a stacked vector of vertex positions, but a matrix of positions.

**Comment by dilevin** [comment]
Correct ! Thanks for catching this, I've fixed it in the code
